package com.krotos.Services;

import com.krotos.Application;
import com.krotos.Objects.Student;
import com.krotos.Objects.StudentWithoutId;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpEntity;
import org.springframework.web.client.RestTemplate;

import java.net.URI;

public class Post {

    private static final Logger log = LoggerFactory.getLogger(Application.class);
    private static final RestTemplate restTemplate = new RestTemplate();
    private static final String myURL = "http://localhost:8080/students";

    //id is autogenerated on servlet so it's different from posted one
    //if id is occupied object won't be posted

    public static void addStudent(Student student) {
        HttpEntity<Student> request = new HttpEntity<>(student);
        Student studentAnswer = restTemplate.postForObject(myURL, request, Student.class);
        if (studentAnswer == null) {
            log.error("addStudent == null. Post unsuccessful --------------------");
        } else {
            log.info(studentAnswer.toString());
        }
    }

    public static void addStudent2(Student student) {
        HttpEntity<Student> request = new HttpEntity<>(student);
        URI location = restTemplate.postForLocation(myURL, request);
        if (location == null) {
            log.error("addStudent2 == null. Post unsuccessful --------------------");
        } else {
            log.info(location.toString());
        }
    }

    //no problems with ID
    public static void addStudentWithoutId(StudentWithoutId studentWithoutId) {
        HttpEntity<StudentWithoutId> request = new HttpEntity<>(studentWithoutId);
        URI location = restTemplate.postForLocation(myURL, request);
        log.info(location.toString());
    }

}
